/**
 * BE CAREFUL!!
 * This file has been auto generated by the yeoman generator:
 *  <%= generatorName %>
 * Any manual changes made to its contents could be overwritten by the
 * yeoman generator when it is run again.
 */
import { fork } from 'redux-saga/effects';

<% sagaList.forEach((saga) => { -%>
import <%= saga.definitionVar -%> from './<%= saga.fileName -%>';
<% }) -%>

export default function*() {
    yield[
<% sagaList.forEach((saga, index) => { -%>
        fork(<%= saga.definitionVar %>)<%= (index < sagaList.length - 1)? ',\n':'\n' -%>
<% }) -%>
    ];
}
